### ISSUE TITLE
Move CI off Travis?

### ISSUE THREAD

**Issue by takluyver** [pypa/pep517#111]
I see that the PSF is paying for the Travis '2 concurrent' plan, and this repo is one of several using that. I don't have a philosophical objection to paying for things if they're valuable, but there are plenty of CI services which offer more than 2 concurrent builds for free, so we could have faster CI and leave Travis time for projects which might be harder to migrate.

Github actions is the currently trendy option, and seems to work well for the most part. But I'm open to using other services so long as they're reasonably snappy and not too much work to maintain.

**Comment by pradyunsg** [comment]
Let's do Github Actions.
