### ISSUE TITLE
Please fix the github releases list

### ISSUE THREAD

**Issue by hexagonrecursion** [pypa/pep517#113]
Currently 0.3 shows up as the latest release according to github. This is *very* misleading.

![screenshot](https://user-images.githubusercontent.com/52621858/110812862-dfac4a80-827f-11eb-8565-869f7630ce6f.png)

**Comment by takluyver** [comment]
Is there a way to tell Github that all tags are releases? Or can we just delete the existing 'releases' in favour of the tags? It's automated so a new release is uploaded to PyPI when a tag is pushed, and I'd rather not have to do something manually on Github for each release in addition.

**Comment by hexagonrecursion** [comment]
> can we just delete the existing 'releases' in favour of the tags?

Try this:
1. Open https://github.com/pypa/pep517/releases/tag/0.3
2. Click "Delete" (it's on the right side of the page)

This should delete the release but keep the tag.

**Comment by pradyunsg** [comment]
Resolved.

**Comment by takluyver** [comment]
Thanks @pradyunsg :-)
