### ISSUE TITLE
Allow fallback from tomli to toml on newer Python

### ISSUE THREAD

**Issue by nanonyme** [pypa/pep517#129]
Please allow falling to toml instead of requiring tomli on new Python 3. tomli is only installable with pep517 which creates a circular dependency that you need pep517 to build pep517.

**Comment by nanonyme** [comment]
Come to that, looks like pep517 needs pep517 to be built so it has circular dependency on itself as well.

**Comment by nanonyme** [comment]
I'm closing this. We clearly just need to bootstrap somehow.

**Comment by takluyver** [comment]
I'm working on a bootstrapping page as part of flit's documentation. On my
phone now, so I can't quickly link it, but it should be easy to find the PR.

**Comment by nanonyme** [comment]
@takluyver it was reasonably straightforward to do, I tried as part of https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/5870 and created a new tool to install wheels that can be told what the build-backend is so it doesn't need to read TOML during bootstrapping.
