### ISSUE TITLE
Callers need better control over backend output

### ISSUE THREAD

**Issue by pfmoore** [pypa/pep517#13]
From the PEP, "The build frontend may capture stdout and/or stderr from the backend". As a specific example, pip currently captures setuptools output and displays it only in debug mode or when an error occurs. Also, if not displaying output, a progress spinner is updated as lines of output are produced. Similar control will be needed under PEP 517.

So, the requirements are, to be able to (on a per-call basis) capture hook output (stdout and/or stderr - pip simply merges the two, which should be sufficient for most cases) and react to it in real time as it's generated line by line.

It's not immediately obvious what the best design here would be. My initial suggestion (not yet validated to confirm that it would satisfy pip's requirements) would be for the wrapper to support a context manager that allows temporarily using a different function to call the subprocess:

```python

def my_runner(cmdline, cwd, env):
    # This is the default, we'd customise this as needed
    # Callers must supply a function that runs the command with the given CWD and env.
    # No return value.
    # Raise an exception if the subprocess errors, or the invocation fails.
    subprocess.check_call(cmdline, cwd, env)

with backend.subprocess_runner(my_runner):
    backend.build_wheel(...)
```

Does anyone have any comments, or alternative design ssuggestions?

**Comment by pfmoore** [comment]
Thanks. Having tested it in pip, I think the right granularity is being able to replace `check_call(cmd, cwd, extra_env)` is about right (although that may just be bias because it matches pip's use case :smile:). But I'm not a huge fan of the context manager, it feels a bit over-engineered. A `runner` kwarg is not unreasonable, but I wasn't sure if I liked changing the calling signatures of the hooks.

See https://github.com/pfmoore/pip/blob/pep517/src/pip/_internal/wheel.py#L682 for how it looks with the context manager version. (Warning: that branch is actively having history rewritten at the moment, so that URL may not be stable long term).

**Comment by takluyver** [comment]
For now, I think whatever makes sense for pip is a good way to go. If we need more flexibility in the future, I like my last idea (a lower level API that prepares argv+env+cwd but doesn't run the subprocess).

**Comment by pfmoore** [comment]
OK, cool. I'm not entirely sure I like the lower-level API (the wrappers are currently really nice, insofar as they feel like you're just calling an in-process API, and I think that's the right level for anything but advanced use) but it depends on what level of control the caller wants. Pip wouldn't want to go any lower level than the current API, as if we did, there'd be little point in not just making our own wrappers, but maybe other projects would want something different.

Like you say, let's take it on a per use case basis. I'll experiment a bit in pip and implement whatever works best back here.

**Comment by pfmoore** [comment]
Good point - I like the Sans IO idea, but like you say doing it cleanly is the key. We'll wait and see how it goes :-)

**Comment by jaraco** [comment]
This issue has impacted the work on #48, because an API caller to generate metadata definitely doesn't want to see pip installing stuff. In that PR, I've taken advantage of the `subprocess_runner` api to supply a `quiet_subprocess_runner`, but even that only affected the hooks and not the pre-hook `pip_install`, which also emits output.

In that PR, I've also manipulated the `pip_install` call to redirect its output to the python `logging` mechanism, with different levels for stdin and stdout. Perhaps this model should be generalized, as it would allow the output to be emitted to stdout, redirected to a file, processed as it arrives, forwarded to syslog, or any number of other approaches.

**Comment by pradyunsg** [comment]
#52 solved this IMO.
