### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/pep517#132]
Hi everyone,

I noticed that many pypa repositories renamed the default branch to `main`. Can we do the same here? Also, I don't know who has the rights to do that.

**Comment by DiddiLeija** [comment]
What do you think?

**Comment by takluyver** [comment]
Sure, why not. Done! :slightly_smiling_face:

**Comment by DiddiLeija** [comment]
Thanks @takluyver!
