### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by pfmoore** [pypa/pep517#17]
I'm going to release a version 0.3, to fix a couple of issues I encountered in pip.

Steps (as far as I recall):

1. Edit `pep517/__init__.py` to update the version, and commit the change.
2. `git tag 0.3`
3. `git push --tags`
4. `flit publish`
5. Create a release on github from tag 0.3

Shout if I forgot anything, otherwise I'll do a release tonight.

**Comment by pfmoore** [comment]
Done, and the steps seemed fine :-)

**Comment by pradyunsg** [comment]
@pfmoore How about adding a `docs/release-process.rst` file or something along those lines?

**Comment by pfmoore** [comment]
Possibly, but I don't really want to become a maintainer for this project, I've got enough on my plate already. I'm just doing what's required to cover pip's needs. (Having commit/release rights means I don't need to bug @takluyver, which is good, but that's all).

I'm happy to merge something if someone else wants to create a PR, though :-)

**Comment by pfmoore** [comment]
> It seemed easier to write new code and invite pip to vendor it than to contribute substantial changes to pip directly.

Strong +1 on this - it's definitely beneficial to have done it this way. One unfortunate thing is that the build environment stuff here is not used in pip - it would be good if this project were the reference implementation for that as well as for the hook calling code. But I guess that's something pip can look at changing in future (I'm not volunteering for that, though!)
