### ISSUE TITLE
Master installs as 0.2 despite 0.3 release

### ISSUE THREAD

**Issue by jaraco** [pypa/pep517#24]
Installing the code in master results in pep517==0.2.

```
pep517 master $ pip install .
Processing /Users/jaraco/code/public/pypa/pep517
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pytoml (from pep517==0.2)
Building wheels for collected packages: pep517
  Building wheel for pep517 (PEP 517) ... done
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-87af9797/wheels/49/cf/b4/c8c7c92c61ca20ee053675caa65bc02da8212c078d75ea49e1
Successfully built pep517
Installing collected packages: pytoml, pep517
Successfully installed pep517-0.2 pytoml-0.1.20
```

I would have expected 0.3+post or 0.4dev or similar.

**Comment by takluyver** [comment]
Not sure how that happened, but I've merged that in with master. Feel free to bump it to whatever in-development format you prefer.

**Comment by jaraco** [comment]
Cool. It installs as 0.3 now. That's satisfactory.

**Comment by pfmoore** [comment]
Sigh, that's probably my fault (again). There's a bit of workflow around making a release that involves creating a github "release" that I muddled my way through online. Unfortunately, I don't see that commit in my local fork here, so I'm not sure how to fix it.

Ah - I see that @takluyver fixed it. Thanks!

We probably need some sort of proper "How to do a release" document...

**Comment by takluyver** [comment]
My usual workflow for making releases is: bump version number, commit, push, wait for CI. Then run `flit publish`, tag, and push the tag. I don't generally bother with Github 'releases'.

**Comment by pfmoore** [comment]
Cool - I only did it because the previous releases were here as github releases. I won't bother in future :-)

**Comment by jaraco** [comment]
GitHub creates releases out of tags automatically.
