### ISSUE TITLE
pep517 should either have wheel as an install dependency, or provide methods to get package dependencies without the wheel tool

### ISSUE THREAD

**Issue by JonasT** [pypa/pep517#39]
pep517 should either have wheel as an install dependency, or provide methods to get package dependencies without the wheel tool. Right now, all the examples in the README don't work properly (except maybe `hooks.build_sys_requires` but that's broken #14 and I'm not sure what it's even supposed to do) without `wheel` installed.

This is why `pep517` really should install `wheel`:

1. Basically, my package builds & installs just fine right now.
2. The promise of `pep517` is that for a properly defined package, I should be able to get metadata (that's the point of the project if I got that right)
3. Therefore, if I install `pep517` and clearly have a working package, I should be able to get its dependencies

This doesn't seem to be possible unless I manually install `wheel` in addition, which I don't think I should be required to do

**Comment by takluyver** [comment]
I think you've maybe misunderstood the aim of this package. It's meant to provide the mechanism for what PEP 517 defines as a frontend to talk to a PEP 517 backend. It's not, by itself, an easy way to get metadata about an arbitrary package.

If you're using the lower-level interface from the 'wrappers' module, which appears to be the case from your other issues, then as the README points out: "you are responsible for ensuring build requirements are available". If your package is built by setuptools+wheel, those packages need to be available. They're not required for all packages; the point of PEP 517 is to allow for different build systems.

If you want to use the higher-level interface from the `envbuild` module to build wheels and sdists, it should create an isolated environment and install the build dependencies listed in your `pyproject.toml`. But the main consumer of this package, pip, handles the environment and build dependencies itself, so the `envbuild` module is not very battle-tested.

**Comment by JonasT** [comment]
Is there an example for this use case of `envbuild`? Because the README only lists building a wheel or sdist, not exactly what I'm looking for (I just want the list of dependencies)

**Comment by takluyver** [comment]
That's all envbuild does. Feel free to look at the source code to see how it does it.

**Comment by JonasT** [comment]
I mean I suppose I could just open up the sdist again to get this info. If there's really no other way that seems fair enough, just seemed a little pointless to me to tar it all up then open it up again :smile:

**Comment by JonasT** [comment]
@takluyver I just tested envbuild and it crashes for me:
```
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/home/jonas/Develop/python-for-android/pythonforandroid/pythonpackage.py", line 78, in _get_metainfo_from_package_folder_unsafe
    build_sdist(path, sdist_path)
  File "/home/jonas/.local/lib/python3.7/site-packages/pep517/envbuild.py", line 151, in build_sdist
    requires, backend = _load_pyproject(source_dir)
  File "/home/jonas/.local/lib/python3.7/site-packages/pep517/envbuild.py", line 19, in _load_pyproject
    with open(os.path.join(source_dir, 'pyproject.toml')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/p4a-dependency-check-bc5noxk3/package/pyproject.toml'
```
I need support for legacy projects with just `setup.py` so if it doesn't provide that, it's not really useful to me :cry: any chance this could be added?

**Comment by takluyver** [comment]
Sorry, I don't think this is the place for legacy support. As the name suggests, it exists to work with the interfaces defined by [PEP 517](https://www.python.org/dev/peps/pep-0517/). Someone could make a wrapper tool that uses either this or `setup.py` commands, but I don't think it belongs here.

**Comment by JonasT** [comment]
isn't there some sort of "pip library"? after all pip supports all of these things, and pretty much all I want is just to get the dependencies similar as pip would (we pretty much do some sort of preprocessing before pip runs, and don't want to break things/stay compatible with whatever pip does afterwards)

**Comment by takluyver** [comment]
Not that I'm aware of. It's a big general issue in the packaging world that everything wants to handle things like pip, but pip itself doesn't have any public Python API. The plan to fix it is to break parts of pip out as separate packages which can be used by other projects, but it's a slow, tricky process. Millions of people use pip every day, so any change can cause lots of problems.

**Comment by takluyver** [comment]
Actually, it is possible to use this interface with `setup.py` projects, because setuptools provides a PEP 517 backend. You'd need to do something like this:

```python
hooks = Pep517HookCaller(src, build_backend='setuptools.build_meta')
```

**Comment by takluyver** [comment]
But whether that will (a) work and (b) do what you want, I'm not sure.

**Comment by JonasT** [comment]
It works, that was my entire point when I suggested a function to read `pyproject.toml` and offer this as a fallback. The problem is pretty much that it takes a while to figure that out as someone without much of a clue, not that it wouldn't be relatively easy to get it to work once you know

**Comment by JonasT** [comment]
Also I just wrote a function that writes a `pyproject.toml` with build-backend = "setuptools.build_meta" and a requires = ["setuptools", "wheel"] if none is present, and that seems to work splendidly as well.

Wouldn't it be nice to have that in pep517 or somewhere else? This all seems to be not *that* much work to put together, but it really lacks some sort of simple function to do this in a generic way for people who aren't like, super familiar with all the build tools and such

**Comment by JonasT** [comment]
One thing I could propose to do as a pull request is to fix this code here https://github.com/pypa/pep517/blob/master/pep517/envbuild.py#L19 breaking when `pyproject.toml` isn't there, and instead returning the defaults I just suggested with requires = ["setuptools", "wheel"] and build-backend = "setputools.build_meta".

As for what I'm doing in my project I made a wrapper now to work around this so this is not urgent for me, so if you have a longer term goal for a better fix then go for it

**Comment by JonasT** [comment]
Closing since at the very least what I initially brought up here as an issue isn't actually one
