### ISSUE TITLE
Build/check should fallback to setuptools unconditionally

### ISSUE THREAD

**Issue by jaraco** [pypa/pep517#49]
In [this comment](https://github.com/pypa/pep517/pull/48#discussion_r287282963), @gaborbernat suggests that the project should unconditionally fallback to setuptools if PEP 517 is not indicated.

That seems like a plausible suggestion, but I'd like to separate that concern from the concern in the PR.

**Comment by takluyver** [comment]
I've closed most of the issues relating to the `build` and `check` layer, but I'm still open to the simple change to make them fallback to setuptools, if people want to implement that. There's already a `compat_system` function implementing such a fallback.
