### ISSUE TITLE
add console script entry point for build

### ISSUE THREAD

**Issue by gaborbernat** [pypa/pep517#54]
Without this pipx cannot install it sadly 👍

**Comment by takluyver** [comment]
From my perspective, it doesn't really make sense to install pep517 through a tool like pipx, on a couple of levels:

1. It's meant to be infrastructure for other tools like pip, not really a user-facing tool itself.
2. You need to use it with different Python versions to build packages for those same versions. For most pure Python packages this won't matter, but in general if you want a wheel for Python 3.7, you have to build it on Python 3.7. So having a single `pep517` command on PATH is not really helpful. Better to use to `python -m` to explicitly control which Python it runs on.

So I'm inclined to leave it without a script entry point. But if other people decide to implement that, I won't object.

**Comment by pradyunsg** [comment]
I am working on the pip build logic now - I will look into the pip build command sometime soon enough. It won't be super soon though.

**Comment by gaborbernat** [comment]
The problem with pip is even if it's implemented will take a longer time to land on users machines, and for now universal wheels and source distribution are perfectly build able with pep517.build.

**Comment by pfmoore** [comment]
You can of course just write your *own* script that uses the `pep517` API to provide a CLI (and install that with pipx if you want, or just run your driver script with with `rwt`).

Not every library has to expose a CLI.

**Comment by gaborbernat** [comment]
> Not every library has to expose a CLI.

I suppose not, but given this felt not that costly I thought I don't have to roll my own and I can use the library itself. Seems I was wrong. 

> You can of course just write your own script

At that point, I might as well implement pip build.

**Comment by takluyver** [comment]
It's not costly in terms of development effort now to add it, but it might be in terms of user expectations later - I think that installing a command implies a higher level of end-user-ness than module commands to be run with `python -m`. It could also cause confusion if you have multiple Pythons on your system, because a `pep517` command would run with whichever Python you installed it in most recently.

**Comment by gaborbernat** [comment]
I'm not sure I agree, in my view ``python -m a`` and console script ``a`` implies the same level end-user access, just different access point.

Judging from your argument pytest should also not offer a ``pytest`` command, as it's certainly very important what pytest version you run from what pytest application. To be fair probably an easier battle here would be maybe as a pipx feature, so it's able to generate the script (potentially versioned).

**Comment by takluyver** [comment]
It certainly has caused me occasional confusion that things like pytest and pip get overwritten as I install them on different Python versions, but for those tools I think the upside outweighs the negatives. But I don't think it makes sense to install either of them with `pipx` - you want them in your working environment, not partitioned off in their own environment.
