### ISSUE TITLE
Default Pep517HookCaller subprocess runner not reverted on exception

### ISSUE THREAD

**Issue by chrahunt** [pypa/pep517#65]
If the scope wrapped by [`Pep517HookCaller.subprocess_runner`](https://github.com/pypa/pep517/blob/09b403216f36859c91b554f8488ae217449423c9/pep517/wrappers.py#L130-L137) raises an exception then the overridden `_subprocess_runner` will not get reverted back to the default. We should have a `try: ... finally: ...` around the yield.

**Comment by takluyver** [comment]
Want to make a pull request?

**Comment by chrahunt** [comment]
I'll try to get to it later today. Suggestions on filename for the tests?

**Comment by takluyver** [comment]
`test_subprocess_runner.py`? Or you could add it in to `test_call_hooks.py`, if you like.
