### ISSUE TITLE
is .bumpversion.cfg used?

### ISSUE THREAD

**Issue by duckinator** [pypa/pep517#68]
I was poking around the codebase and noticed that [.bumpversion.cfg](https://github.com/pypa/pep517/blob/41df3ea/.bumpversion.cfg) says the current version is 0.5.0, but there's been two releases since then.

Is bumpversion still being used?

**Comment by takluyver** [comment]
*ahem* - @jaraco kindly set up automatic releases from Travis CI. But I keep forgetting about that, and doing releases from my own computer the way I'm used to, bypassing all of the automation machinery.

**Comment by duckinator** [comment]
haha, no worries, i've done similar before. :stuck_out_tongue:
