### ISSUE TITLE
pep517.build warns about missing author_email field

### ISSUE THREAD

**Issue by jugmac00** [pypa/pep517#73]
I ported a very old package to Python 3, of which I know the author, but not his email address. Also, I'd think he does not want to get involved any more with this 16 year old package.

In order to create a package I followed Hynek's guide at
https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

My setup.py contains an author, but no author_email field and me as maintainer.

When I do a `python -m pep517.build .` I get the following warning:
```
warning: Check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too
```

There was a quick discussion over at 
https://discuss.python.org/t/which-fields-are-required-for-a-setup-py-especially-is-author-required/2705/2
with different proposed solutions.

I created a test package and uploaded it at test.pypi.org with the author field, but without an author_email field - looks totally valid to me:
https://test.pypi.org/project/Products.ZopeTree/2.0.2.dev0/

Where is the information coming from that `author_email` **must** be supplied - while it need not as it seems.

Is it possible to drop this warning? Or change its wording to "should be provided"?

If it is a "must" requirement I'd expect the build to fail.

**Comment by pganssle** [comment]
I think maybe we should migrate this to the setuptools repo, because it seems like this warning is being generated by `setuptools` or `distutils`.

Presumably we can solve it by adjusting the wording, since I see no such requirement in [the specification](https://packaging.python.org/specifications/core-metadata/#author).

**Comment by jugmac00** [comment]
Paul, thank you for your feedback. I dug a bit deeper and the warning comes from `distutils` which is located in the `cpython` repository.

https://github.com/python/cpython/blob/d5a5a33f12b60129d57f9b423b77d2fcba506834/Lib/distutils/command/check.py#L97-L100

I was not sure whether it is necessary to create an issue for this minor wording adjustment, but I did it anyway:
https://bugs.python.org/issue38914

I'll also prepare a pr.

**Comment by takluyver** [comment]
Closing here as it seems like it's not related to pep517. :-)
