### ISSUE TITLE
Add --quiet options to build and check

### ISSUE THREAD

**Issue by Julian** [pypa/pep517#77]
It'd be nice, particularly for `pep517.check`, to selectively show less noisy output (e.g. simply whether things were successfully built).

**Comment by pradyunsg** [comment]
PRs welcome. :)

**Comment by takluyver** [comment]
We've come to an agreement that the functionality to create isolated build environments and install build dependencies will live in the [PyPA build project](https://github.com/pypa/build). The `pep517` library will continue to exist as the lower-level piece to work with the interfaces defined by [PEP 517](https://www.python.org/dev/peps/pep-0517/), but the `pep517.envbuild` module and the little command-line interfaces which use it (`pep517.build`, `pep517.check` and `pep517.meta`) will gradually be deprecated and eventually removed as `build` becomes more stable. See #91 for more on that process.

So I'm closing this, as there won't be any further significant work here on these pieces. Hopefully `build` already meets your needs better.
