### ISSUE TITLE
Need a PyPI release

### ISSUE THREAD

**Issue by pfmoore** [pypa/pep517#9]
In order to integrate with pip's vendoring mechanism, we need to be able to `pip install` this package. Ultimately, this means a pip release. In the short term, we can't vendor from github, because prior to the adoption of PEP 517, pip can only install `setup.py` based projects from source...

This is a short term issue during the development of pip's PEP 517 support, but I wanted to note it here so that it doesn't get forgotten.

**Comment by takluyver** [comment]
I'm happy to make a release whenever suits you. You're also a maintainer on PyPI, so you can cut a release yourself if you like: `flit publish` should do it.

**Comment by takluyver** [comment]
(After updating the version number in `pep517/__init__.py`)

**Comment by pfmoore** [comment]
My only problem with releasing to PyPI is that I'm not very clear on the "project admin" side of PyPI, but I'm happy to give it a go and add you as an owner, if that's all that's needed.

**Comment by takluyver** [comment]
There's already a version 0.1 on PyPI, so it shouldn't need any special admin actions: https://pypi.org/project/pep517/

**Comment by pfmoore** [comment]
Huh. My mistake - I'd checked (multiple times) and not seen that. Ah, it appears that if you search for the explicit string "pep517", the project with that name is displayed on the second pages of the search results. Looks like warehouse search is still as flaky as the old PyPI version :-(

I'll release a new version in that case, to capture the changes we've put in.

**Comment by pfmoore** [comment]
Done. That was easy :-)
