### ISSUE TITLE
Set up webhook for RTD

### ISSUE THREAD

**Issue by takluyver** [pypa/pep517#99]
I've just set up docs on Readthedocs: https://pep517.readthedocs.io/en/latest/index.html

However, I don't have permission to create the webhook for new commits to be built automatically. Please could someone with the right access go to https://readthedocs.org/dashboard/pep517/integrations/135801/ and click the 'Resync' button to wire it up? 

Thanks!

**Comment by pfmoore** [comment]
Sorry, I don't have the access. I'm surprised you don't though - you show as the admin/owner on Readthedocs...

**Comment by takluyver** [comment]
I have the access on RTD itself, but not the Github permissions. Sorry, I didn't think this through - someone would need both sets of permissions to set it up. I've just added you as a maintainer on RTD; could you try https://readthedocs.org/dashboard/pep517/integrations/135801/ again?

**Comment by pfmoore** [comment]
"Webhook activation failed. Make sure you have the necessary permissions."

Rather than you giving me more permissions (which TBH I don't really want) what permissions do you need? Maybe I can grant them to you.

**Comment by takluyver** [comment]
That's what I see too. :-)

I assume I would need access to configure the settings for this repo on Github. I can't see 'Settings' in the bar with 'Code', 'Issues', etc. - the last tab is 'Settings' in my personal repositories.

**Comment by pfmoore** [comment]
You and I both had "Write" access to the pep517 project. I have extra privileges as I'm a PyPA "Owner" and you are a PyPA "Member". I just gave you "Admin" access to the pep517 project, so you should now be able to do whatever you need to. (You'll have "Settings" access, at least).

**Comment by takluyver** [comment]
Thanks Paul, that did it. :smiley:
